/**
 * Error codes constants cho UC-IMM-02 Yêu cầu gia hạn phiên họp và UC-IMM-03 Phê duyệt/từ chối gia hạn.
 * Sử dụng trong LiveMeetingService để throw NestJS exception với mã lỗi chuẩn hóa.
 */
export const MEETING_EXTENSION_ERRORS = {
  // UC-IMM-02 errors
  MEETING_NOT_FOUND: 'MEETING_NOT_FOUND',
  MEETING_EXTENSION_NOT_HOST: 'MEETING_EXTENSION_NOT_HOST',
  MEETING_EXTENSION_NOT_IN_PROGRESS: 'MEETING_EXTENSION_NOT_IN_PROGRESS',
  MEETING_EXTENSION_NO_ACTIVE_BOOKING: 'MEETING_EXTENSION_NO_ACTIVE_BOOKING',
  MEETING_EXTENSION_INVALID_DURATION: 'MEETING_EXTENSION_INVALID_DURATION',
  MEETING_EXTENSION_LIMIT_EXCEEDED: 'MEETING_EXTENSION_LIMIT_EXCEEDED',
  MEETING_EXTENSION_NO_APPROVER: 'MEETING_EXTENSION_NO_APPROVER',
  MEETING_EXTENSION_MANAGER_NOTIFICATION_FAILED:
    'MEETING_EXTENSION_MANAGER_NOTIFICATION_FAILED',
  // UC-IMM-03 errors
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  REQUEST_ALREADY_PROCESSED: 'REQUEST_ALREADY_PROCESSED',
  MEETING_NOT_ACTIVE: 'MEETING_NOT_ACTIVE',
  ROOM_CONFLICT: 'ROOM_CONFLICT',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
} as const;

export type MeetingExtensionErrorCode =
  (typeof MEETING_EXTENSION_ERRORS)[keyof typeof MEETING_EXTENSION_ERRORS];
