export const MEETING_WARNING_ERRORS = {
  MEETING_NOT_FOUND_FOR_SCHEDULING: 'MEETING_NOT_FOUND_FOR_SCHEDULING',
  MEETING_NOT_IN_PROGRESS_FOR_SCHEDULING: 'MEETING_NOT_IN_PROGRESS_FOR_SCHEDULING',
  MEETING_END_TIME_NULL: 'MEETING_END_TIME_NULL',
  WARNING_SCHEDULING_SKIPPED: 'WARNING_SCHEDULING_SKIPPED',
  WARNING_ENQUEUE_FAILED: 'WARNING_ENQUEUE_FAILED',
  WARNING_CANCEL_FAILED: 'WARNING_CANCEL_FAILED',
  // UC-IMM-13 error codes (bổ sung sau UC-IMM-12 codes)
  MEETING_NOT_FOUND_FOR_WARNING: 'MEETING_NOT_FOUND_FOR_WARNING',
  MEETING_NOT_IN_PROGRESS_FOR_WARNING: 'MEETING_NOT_IN_PROGRESS_FOR_WARNING',
  WARNING_ALREADY_SENT: 'WARNING_ALREADY_SENT',
  HOST_NOT_RESOLVED: 'HOST_NOT_RESOLVED',
  CONFLICT_DETECTION_FAILED: 'CONFLICT_DETECTION_FAILED',
  CONFLICT_BUFFER_CONFIG_INVALID: 'CONFLICT_BUFFER_CONFIG_INVALID',
  WARNING_NOTIFICATION_CREATE_FAILED: 'WARNING_NOTIFICATION_CREATE_FAILED',
  WARNING_WEBSOCKET_PUSH_FAILED: 'WARNING_WEBSOCKET_PUSH_FAILED',
  BACKGROUND_JOB_UPDATE_FAILED: 'BACKGROUND_JOB_UPDATE_FAILED',
  MEETING_EVENT_CREATE_FAILED: 'MEETING_EVENT_CREATE_FAILED',
} as const;
