/**
 * Error codes constants cho UC-IMM-01 Bắt đầu phiên họp.
 * Sử dụng trong LiveMeetingService để throw NestJS exception với mã lỗi chuẩn hóa.
 */
export const MEETING_START_ERRORS = {
  MEETING_NOT_FOUND: 'MEETING_NOT_FOUND',
  MEETING_NOT_IN_SCHEDULED_STATUS: 'MEETING_NOT_IN_SCHEDULED_STATUS',
  MEETING_ALREADY_STARTED: 'MEETING_ALREADY_STARTED',
  MEETING_ALREADY_COMPLETED: 'MEETING_ALREADY_COMPLETED',
  MEETING_CANCELLED: 'MEETING_CANCELLED',
  MEETING_PENDING_APPROVAL: 'MEETING_PENDING_APPROVAL',
  MEETING_IN_DRAFT_STATUS: 'MEETING_IN_DRAFT_STATUS',
  MEETING_START_TOO_EARLY: 'MEETING_START_TOO_EARLY',
  MEETING_START_WINDOW_EXPIRED: 'MEETING_START_WINDOW_EXPIRED',
  MEETING_START_AMBIGUOUS_DEVICE_MATCH: 'MEETING_START_AMBIGUOUS_DEVICE_MATCH',
} as const;

export type MeetingStartErrorCode = (typeof MEETING_START_ERRORS)[keyof typeof MEETING_START_ERRORS];
