/**
 * Error codes constants cho In-Meeting Notes (UC-102/103/104) va View Meeting Notes (UC-IMM-10).
 * Su dung trong LiveMeetingService de throw NestJS exception voi ma loi chuan hoa.
 */
export const MEETING_NOTE_ERRORS = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  NOTE_HOST_ONLY: 'NOTE_HOST_ONLY',
  MEETING_NOT_FOUND: 'MEETING_NOT_FOUND',
  MEETING_NOT_IN_PROGRESS: 'MEETING_NOT_IN_PROGRESS',
  NOTE_SYSTEM_TYPE_FORBIDDEN: 'NOTE_SYSTEM_TYPE_FORBIDDEN',
  MEETING_STATUS_NOT_VIEWABLE: 'MEETING_STATUS_NOT_VIEWABLE',
  NOT_A_MEETING_PARTICIPANT: 'NOT_A_MEETING_PARTICIPANT',
  INVALID_DATE_RANGE: 'INVALID_DATE_RANGE',
} as const;

export type MeetingNoteErrorCode = (typeof MEETING_NOTE_ERRORS)[keyof typeof MEETING_NOTE_ERRORS];