/**
 * Mã lỗi cho luồng khách ngoài công ty (guest access).
 *
 * Nguyên tắc quan trọng: `GUEST_INVITE_INVALID` được dùng CHUNG cho cả "id
 * không tồn tại" và "hash sai" — cố ý KHÔNG phân biệt, để không biến endpoint
 * công khai thành công cụ dò `externalParticipantId` hợp lệ (spec FR-GLA-028).
 */
export const GUEST_ACCESS_ERROR_CODES = {
  GUEST_INVITE_INVALID: 'GUEST_INVITE_INVALID',
  GUEST_INVITE_EXPIRED: 'GUEST_INVITE_EXPIRED',
  GUEST_INVITE_REVOKED: 'GUEST_INVITE_REVOKED',
  GUEST_JOIN_WINDOW_CLOSED: 'GUEST_JOIN_WINDOW_CLOSED',
  GUEST_MEETING_CANCELLED: 'GUEST_MEETING_CANCELLED',
  GUEST_EMAIL_MISSING: 'GUEST_EMAIL_MISSING',
  GUEST_OTP_INVALID: 'GUEST_OTP_INVALID',
  GUEST_OTP_BLOCKED: 'GUEST_OTP_BLOCKED',
  GUEST_OTP_TOO_MANY_REQUESTS: 'GUEST_OTP_TOO_MANY_REQUESTS',
  GUEST_SESSION_INVALID: 'GUEST_SESSION_INVALID',
  GUEST_MEETING_SCOPE_MISMATCH: 'GUEST_MEETING_SCOPE_MISMATCH',
  GUEST_LOBBY_PENDING: 'GUEST_LOBBY_PENDING',
  NOT_MEETING_HOST: 'NOT_MEETING_HOST',
} as const;

export type GuestAccessErrorCode =
  (typeof GUEST_ACCESS_ERROR_CODES)[keyof typeof GUEST_ACCESS_ERROR_CODES];
