export const TRANSCRIPTION_ERROR_CODES = {
  MEETING_NOT_FOUND: 'MEETING_NOT_FOUND',
  RECORDING_SESSION_NOT_FOUND: 'RECORDING_SESSION_NOT_FOUND',
  SOURCE_MEDIA_NOT_FOUND: 'SOURCE_MEDIA_NOT_FOUND',
  TRANSCRIPTION_JOB_ALREADY_RUNNING: 'TRANSCRIPTION_JOB_ALREADY_RUNNING',
  TRANSCRIPTION_DISABLED: 'TRANSCRIPTION_DISABLED',
  AUDIO_TOO_LONG_FOR_LOCAL_PROFILE: 'AUDIO_TOO_LONG_FOR_LOCAL_PROFILE',
  CUDA_NOT_AVAILABLE_FOR_PROFILE: 'CUDA_NOT_AVAILABLE_FOR_PROFILE',
  UNSUPPORTED_MEDIA_FORMAT: 'UNSUPPORTED_MEDIA_FORMAT',
  SEGMENT_NOT_FOUND: 'SEGMENT_NOT_FOUND',
  TRANSCRIPT_NOT_FOUND: 'TRANSCRIPT_NOT_FOUND',
} as const;

export type TranscriptionErrorCode =
  (typeof TRANSCRIPTION_ERROR_CODES)[keyof typeof TRANSCRIPTION_ERROR_CODES];
