export const AUTH_REPOSITORY_TOKENS = {
  USERS_AUTH_REPOSITORY: 'USERS_AUTH_REPOSITORY',
  AUTHZ_READ_REPOSITORY: 'AUTHZ_READ_REPOSITORY',
  USER_SESSIONS_REPOSITORY: 'USER_SESSIONS_REPOSITORY',
  AUTH_AUDIT_REPOSITORY: 'AUTH_AUDIT_REPOSITORY',
} as const;
