export const AUTH_ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_INACTIVE: 'AUTH_ACCOUNT_INACTIVE',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  AUTH_ACCOUNT_STATUS_NOT_ALLOWED: 'AUTH_ACCOUNT_STATUS_NOT_ALLOWED',
  AUTH_TOO_MANY_ATTEMPTS: 'AUTH_TOO_MANY_ATTEMPTS',
  AUTH_SESSION_CREATE_FAILED: 'AUTH_SESSION_CREATE_FAILED',
  AUTH_TOKEN_GENERATION_FAILED: 'AUTH_TOKEN_GENERATION_FAILED',
  AUTH_OTP_INVALID_OR_EXPIRED: 'AUTH_OTP_INVALID_OR_EXPIRED',
  AUTH_ACCOUNT_RESTRICTED: 'AUTH_ACCOUNT_RESTRICTED',
} as const;

